// <auto-generated />
using System;
using Empite.TribechimpService.PaymentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Empite.TribechimpService.PaymentService.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180725112659_ispaidproperty")]
    partial class ispaidproperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Empite.TribechimpService.PaymentService.Domain.Entity.InvoiceRelated.ConfiguredPaymentGateway", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GatewayName");

                    b.Property<bool>("IsEnabled");

                    b.HasKey("Id");

                    b.ToTable("ConfiguredPaymentGateways");
                });

            modelBuilder.Entity("Empite.TribechimpService.PaymentService.Domain.Entity.InvoiceRelated.InvoiceContact", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<Guid?>("DeletedBy");

                    b.Property<string>("Email");

                    b.Property<string>("OrganizationId");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<Guid?>("UpdatedBy");

                    b.Property<string>("ZohoContactUserId");

                    b.Property<string>("ZohoPrimaryContactId");

                    b.HasKey("UserId");

                    b.HasIndex("ZohoContactUserId");

                    b.ToTable("InvoiceContacts");
                });

            modelBuilder.Entity("Empite.TribechimpService.PaymentService.Domain.Entity.InvoiceRelated.InvoiceHistory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<Guid?>("DeletedBy");

                    b.Property<int>("InvoiceStatus");

                    b.Property<DateTime?>("PaymentRecordedDate");

                    b.Property<string>("PurcheseId");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<Guid?>("UpdatedBy");

                    b.Property<string>("ZohoInvoiceId");

                    b.HasKey("Id");

                    b.HasIndex("PurcheseId");

                    b.HasIndex("ZohoInvoiceId");

                    b.ToTable("InvoiceHistories");
                });

            modelBuilder.Entity("Empite.TribechimpService.PaymentService.Domain.Entity.InvoiceRelated.Purchese", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<Guid?>("DeletedBy");

                    b.Property<string>("InvoiceContactUserId");

                    b.Property<string>("InvoiceName");

                    b.Property<int>("InvoiceStatus");

                    b.Property<int>("InvoiceType");

                    b.Property<bool>("IsPaidForThisMonth");

                    b.Property<Guid?>("ReferenceGuid");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<Guid?>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceContactUserId");

                    b.HasIndex("ReferenceGuid");

                    b.ToTable("Purcheses");
                });

            modelBuilder.Entity("Empite.TribechimpService.PaymentService.Domain.Entity.InvoiceRelated.ZohoInvoiceJobQueue", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<Guid?>("DeletedBy");

                    b.Property<bool>("IsSuccess");

                    b.Property<int>("JobType");

                    b.Property<string>("JsonData")
                        .HasColumnType("longtext");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<int>("ReTryCount");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<Guid?>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("ZohoInvoiceJobQueues");
                });

            modelBuilder.Entity("Empite.TribechimpService.PaymentService.Domain.Entity.InvoiceRelated.ZohoItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<Guid?>("DeletedBy");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<double>("Rate");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<Guid?>("UpdatedBy");

                    b.Property<string>("ZohoItemId");

                    b.HasKey("Id");

                    b.HasIndex("ZohoItemId");

                    b.ToTable("ZohoItems");
                });

            modelBuilder.Entity("Empite.TribechimpService.PaymentService.Domain.Entity.InvoiceRelated.ZohoItem_Purchese", b =>
                {
                    b.Property<string>("RecurringInvoiceId");

                    b.Property<string>("ZohoItemId");

                    b.Property<int>("Qty");

                    b.HasKey("RecurringInvoiceId", "ZohoItemId");

                    b.HasIndex("ZohoItemId");

                    b.ToTable("ZohoItem_Purchese");
                });

            modelBuilder.Entity("Empite.TribechimpService.PaymentService.Domain.Entity.InvoiceRelated.InvoiceHistory", b =>
                {
                    b.HasOne("Empite.TribechimpService.PaymentService.Domain.Entity.InvoiceRelated.Purchese", "Purchese")
                        .WithMany("InvoiceHistories")
                        .HasForeignKey("PurcheseId");
                });

            modelBuilder.Entity("Empite.TribechimpService.PaymentService.Domain.Entity.InvoiceRelated.Purchese", b =>
                {
                    b.HasOne("Empite.TribechimpService.PaymentService.Domain.Entity.InvoiceRelated.InvoiceContact", "InvoiceContact")
                        .WithMany("Invoices")
                        .HasForeignKey("InvoiceContactUserId");
                });

            modelBuilder.Entity("Empite.TribechimpService.PaymentService.Domain.Entity.InvoiceRelated.ZohoItem_Purchese", b =>
                {
                    b.HasOne("Empite.TribechimpService.PaymentService.Domain.Entity.InvoiceRelated.Purchese", "Purchese")
                        .WithMany("ZohoItems")
                        .HasForeignKey("RecurringInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Empite.TribechimpService.PaymentService.Domain.Entity.InvoiceRelated.ZohoItem", "ZohoItem")
                        .WithMany("RecurringInvoices")
                        .HasForeignKey("ZohoItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
